Transit_Hualqui/urls.py
from django.urls import path
from Transit_Hualqui import views
app_name = 'transit'


urlpatterns = [
    path('home', views.home, name='home'),
    path('persona', views.PersonaListView.as_view(), name='persona-list'),
    path('trabajador', views.listTrabajadores, name='trabajador-list'),
    path('usuario', views.listUsuarios, name='usuario-list'),
    path('usuario/infracciones/<int:id>', views.listInfracciones, name='usuario-infracciones'),
    path('usuario/apelaciones/<int:id>', views.listApelaciones, name='usuario-apelaciones'),
    path('usuario/apelaciones/aceptar/<int:id>', views.aprobarApelacion, name='acept-apelacion'),
    path('usuario/apelaciones/rechazar/<int:id>', views.rechazarApelacion, name='reject-apelacion'),
    path('usuario/autos/<int:id>', views.listAutos, name='usuario-autos'),
    #path('persona/create', views.PersonaCreateView.as_view(), name='persona-create'),
    path('persona/<int:pk>', views.PersonaDetailView.as_view(), name='persona-detail'),   
    path('persona/<int:pk>/update', views.PersonaUpdateView.as_view(), name='persona-update'), 
    path('persona/delete/<int:id>', views.DeletePersona, name='persona-delete'),
    path('multa', views.MultaListView.as_view(), name='multa-list'),
    path('multa/create', views.MultaCreateView.as_view(), name='multa-create'),
    path('multa/<int:pk>', views.MultaDetailView.as_view(), name='multa-detail'),   
    path('multa/<int:pk>/update', views.MultaUpdateView.as_view(), name='multa-update'), 
    path('multa/<int:pk>/delete', views.MultaDeleteView.as_view(), name='multa-delete'),
    path('multa/usuario', views.searchMulta, name='search-multas'),
    path('multa/usuario/<int:id>', views.showMultas, name='show-multas'),
    path('calle', views.CalleListView.as_view(), name='calle-list'),
    path('calle/create', views.CalleCreateView.as_view(), name='calle-create'),
    path('calle/<int:pk>', views.CalleDetailView.as_view(), name='calle-detail'),   
    path('calle/<int:pk>/update', views.CalleUpdateView.as_view(), name='calle-update'), 
    path('calle/<int:pk>/delete', views.CalleDeleteView.as_view(), name='calle-delete'),
    path('auto', views.AutoListView.as_view(), name='auto-list'),
    path('auto/create', views.AutoCreateView.as_view(), name='auto-create'),
    path('auto/<int:pk>', views.AutoDetailView.as_view(), name='auto-detail'),   
    path('auto/<int:pk>/update', views.AutoUpdateView.as_view(), name='auto-update'), 
    path('auto/<int:pk>/delete', views.AutoDeleteView.as_view(), name='auto-delete'),
    path('apelacion', views.ApelacionListView.as_view(), name='apelacion-list'),
    path('apelacion/create', views.ApelacionCreateView.as_view(), name='apelacion-create'),
    path('apelacion/<int:pk>', views.ApelacionDetailView.as_view(), name='apelacion-detail'),   
    path('apelacion/<int:pk>/update', views.ApelacionUpdateView.as_view(), name='apelacion-update'), 
    path('apelacion/<int:pk>/delete', views.ApelacionDeleteView.as_view(), name='apelacion-delete'),
]

auth_login/urls.py
from django.urls import path, include
from auth_login import views

app_name = 'auth'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('profile/purchases/<int:id>', views.Multas_historial, name='purchases'),
    path('profile/edit', views.editProfile, name='edit'),
    path('profile/change_password', views.change_password, name='change_password'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('transit/', include('Transit_Hualqui.urls')),
    path('auth/', include('auth_login.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Transit_Hualqui/models.py
from django.db import models
from django.contrib.auth.models import User
class TipoPersona(models.Model):
    name = models.CharField(max_length=20, unique=True)

    def __str__(self):
        return self.name

class Persona(models.Model):
    Genders = (
	    ('M', 'Mujer'),
	    ('H', 'Hombre'),
	    ('O', 'Otro'),
    )
    Estados = (
	    ('In', 'Inactivo'),
	    ('Ac', 'Activo'),
	    ('Bl', 'Bloqueado'),
    )

    # Al desplegar un CharField con un choices saldrá un cuadro de opciones
    gender = models.CharField(max_length=10, choices=Genders)
    age = models.PositiveIntegerField(default=1)
    run_persona  = models.CharField(max_length=12, unique=True, default=1)
    fecha_nacimiento = models.DateField()
    tipo_persona = models.ForeignKey(TipoPersona, on_delete=models.CASCADE, default=1)
    user = models.OneToOneField(User, on_delete=models.CASCADE, default=1)
    estado = models.CharField(max_length=10, choices=Estados)
    def __str__(self):
        return self.run_persona

    def gender_verbose(self):
        return dict(Persona.Genders)[self.gender]

    def estado_verbose(self):
        return dict(Persona.Estados)[self.estado]


class Auto(models.Model):
    patente = models.CharField(max_length=10, unique=True)
    run_persona_a  = models.ForeignKey(Persona, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return self.patente


class Calle(models.Model):
    Sentidos = (
        ('Am', 'Ambos'), 
        ('Un', 'Unico'),
    )
    id_via = models.PositiveIntegerField()
    nombre_via = models.CharField(max_length=10, unique=True)
    sentido = models.CharField(max_length=20, choices=Sentidos)
    velocidad_maxima = models.PositiveIntegerField()

    def __str__(self):
        return self.nombre_via

    def sentido_verbose(self):
        return dict(Calle.Sentidos)[self.sentido]


class Multa(models.Model):
    RangoInfraccion = (
	('G', 'Grave'),
	('Gr', 'Gravisima'),
	('O', 'Otro'),
)
    run_infractor  = models.ForeignKey(Persona, on_delete=models.CASCADE, related_name='rut_infractor', default=1)
    run_trabajador = models.ForeignKey(Persona, on_delete=models.CASCADE, default=1)
    patente_m = models.ForeignKey(Auto, on_delete=models.CASCADE,default=1)
    fecha_hr = models.DateTimeField()
    monto = models.PositiveIntegerField()
    tipo_monto = models.CharField(max_length=200)
    id_via_m = models.ForeignKey(Calle, on_delete=models.CASCADE, default=1)
    gravedad = models.CharField(max_length=200, choices=RangoInfraccion)

    def __str__(self):
        return str(self.id)

    def gravedad_verbose(self):
        return dict(Multa.RangoInfraccion)[self.gravedad]

class Apelacion(models.Model):
    id_multa_a = models.ForeignKey(Multa, on_delete=models.CASCADE)
    run_persona_a = models.ForeignKey(Persona, on_delete=models.CASCADE)
    descripcion = models.TextField(max_length=1000)
    estado = models.CharField(max_length=15)
    fecha_hr_a = models.DateTimeField()

    def __str__(self):
        return str(self.id_multa_a)

Transit_Hualqui/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm
Genders = (
	('M', 'Mujer'),
	('H', 'Hombre'),
	('O', 'Otro'),
)


Estados = (
	('In', 'Inactivo'),
	('Ac', 'Activo'),
	('Bl', 'Bloqueado'),
)

class MultaForm(forms.Form):
    rut =  forms.CharField(label='Rut', help_text="Rut con el siguiente formato 1234568-9")

Transit_Hualqui/views.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.urls import reverse_lazy
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from Transit_Hualqui.forms import MultaForm
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.db import IntegrityError
from django.core.exceptions import ObjectDoesNotExist
from Transit_Hualqui.models import (
    Apelacion,
    Auto,
    Calle,
    Multa,
    Persona,
    TipoPersona,
)


def home(request):
    data = {}
    template_name = 'home.html'

    return render(request, template_name, data)

@login_required
def listTrabajadores(request):
    data = {}
    template_name = 'trabajadores.html'
    data['personas'] = Persona.objects.filter(tipo_persona=2)

    return render(request, template_name, data)

@login_required
def listUsuarios(request):
    data = {}
    template_name = 'usuarios.html'
    data['personas'] = Persona.objects.filter(tipo_persona=3)

    return render(request, template_name, data)

@login_required
def listInfracciones(request, id):
    data = {}
    template_name = 'multas_usuario.html'
    data['multas'] = Multa.objects.filter(run_infractor=id)

    return render(request, template_name, data)

@login_required
def listApelaciones(request, id):
    data = {}
    template_name = 'apelacione_usuario.html'
    data['apelaciones'] = Apelacion.objects.filter(run_persona_a=id)

    return render(request, template_name, data)
"""
@login_required
def aprobarApelacion(request, id):
    data = {}
    template_name = 'confirmarAp.html'
    apelacion = Apelacion.objects.get(pk=id)
    apelacion.estado = "Aceptado"
    apelacion.save()

    return render(request, template_name, data)
"""

@login_required
def aprobarApelacion(request, id):
    data = {}
    template_name = 'confirmarAp.html'
    data['apelacion'] = Apelacion.objects.get(pk=id)
    if request.method == 'POST':
        data['apelacion'].estado = 'Aceptado'
        data['apelacion'].save()
        return redirect('transit:usuario-list')
    return render(request, template_name, data)

@login_required
def rechazarApelacion(request, id):
    data = {}
    template_name = 'rechazarAp.html'
    data['apelacion'] = Apelacion.objects.get(pk=id)
    if request.method == 'POST':
        data['apelacion'].estado = 'Rechazado'
        data['apelacion'].save()
        return redirect('transit:usuario-list')
    return render(request, template_name, data)

@login_required
def listAutos(request, id):
    data = {}
    template_name = 'autos-usuario.html'
    data['autos'] = Auto.objects.filter(run_persona_a=id)

    return render(request, template_name, data)


def searchMulta(request):
    data = {}
    template_name = 'usuario-multa-consulta.html'
    data['form'] = MultaForm(request.POST or None)

    if request.method == 'POST':
        if data['form'].is_valid():
            try:
                rut = request.POST['rut']
                persona = Persona.objects.get(run_persona=rut)
                
                messages.add_message(
                    request,
                    messages.SUCCESS,
                    'Consulta realizada con exito'
                )
                return redirect('transit:show-multas', id=persona.id)
            except ObjectDoesNotExist:
                persona = None
                messages.add_message(
                    request,
                    messages.ERROR,
                    'Rut no registra multas',
                )

            except IntegrityError as ie:
                messages.add_message(
                    request,
                    messages.ERROR,
                    'Problemas al realizar la consulta: {error}.'.format(
                        error=str(ie))
                )
            
        else:
            messages.add_message(
                request,
                messages.ERROR,
                'Problemas al realizar la consulta',
            )
        
    return render(request, template_name, data)

def showMultas(request, id):
    data = {}
    template_name = 'usuario-multa.html'
    try:
        data['multas'] = Multa.objects.filter(run_infractor=id)
        messages.add_message(
            request,
            messages.SUCCESS,
            'Consulta realizada con exito'
        )
    except ObjectDoesNotExist:
        data['multas'] = None
        messages.add_message(
            request,
            messages.ERROR,
            'Rut no registra multas',
        )

    return render(request, template_name, data)


@method_decorator(login_required, name='dispatch')
class PersonaListView(ListView):
    model = Persona
    template_name = 'listado_persona.html'
    context_object_name = 'personas'
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super(PersonaListView, self).get_context_data(**kwargs)
        personas = self.get_queryset()
        page = self.request.GET.get('page')
        paginator = Paginator(personas, self.paginate_by)
        try:
            personas = paginator.page(page)
        except PageNotAnInteger:
            personas = paginator.page(1)
        except EmptyPage:
            personas = paginator.page(paginator.num_pages)
        context['personas'] = personas
        return context

@method_decorator(login_required, name='dispatch')
class PersonaCreateView(CreateView):
    model = Persona
    template_name = 'create.html'
    fields = ('gender', 'age', 'run_persona', 'fecha_nacimiento', 'tipo_persona')
    success_url = reverse_lazy('transit:persona-list')

@method_decorator(login_required, name='dispatch')
class PersonaDetailView(DetailView):
    model = Persona
    template_name = 'detail.html'
    context_object_name = 'personas'

@method_decorator(login_required, name='dispatch')
class PersonaUpdateView(UpdateView):
    model = Persona
    template_name = 'update.html'
    context_object_name = 'personas'
    fields = ('gender', 'age', 'run_persona', 'fecha_nacimiento', 'tipo_persona')

    def get_success_url(self):
        return reverse_lazy('transit:persona-detail', kwargs={'pk': self.object.id})

@login_required
def DeletePersona(request, id):
    data = {}
    template_name = 'delete.html'
    data['persona'] = Persona.objects.get(pk=id)
    if request.method == 'POST':
        data['persona'].estado = 'In'
        data['persona'].save()
        return redirect('transit:persona-list')
    return render(request, template_name, data)


@method_decorator(login_required, name='dispatch')
class MultaListView(ListView):
    model = Multa
    template_name = 'listado_multa.html'
    context_object_name = 'multas'
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super(MultaListView, self).get_context_data(**kwargs)
        multas = self.get_queryset()
        page = self.request.GET.get('page')
        paginator = Paginator(multas, self.paginate_by)
        try:
            multas = paginator.page(page)
        except PageNotAnInteger:
            multas = paginator.page(1)
        except EmptyPage:
            multas = paginator.page(paginator.num_pages)
        context['multas'] = multas
        return context

@method_decorator(login_required, name='dispatch')
class MultaCreateView(CreateView):
    model = Multa
    template_name = 'create-multa.html'
    fields = ('run_infractor',
    'run_trabajador',
    'patente_m',
    'fecha_hr',
    'monto',
    'tipo_monto',
    'id_via_m',
    'gravedad',
    )
    success_url = reverse_lazy('transit:multa-list')

@method_decorator(login_required, name='dispatch')
class MultaDetailView(DetailView):
    model = Multa
    template_name = 'detail-multa.html'
    context_object_name = 'multas'

@method_decorator(login_required, name='dispatch')
class MultaUpdateView(UpdateView):
    model = Multa
    template_name = 'update_multa.html'
    context_object_name = 'multas'
    fields = ('run_infractor',
    'run_trabajador',
    'patente_m',
    'fecha_hr',
    'monto',
    'tipo_monto',
    'id_via_m',
    'gravedad',
    )

    def get_success_url(self):
        return reverse_lazy('transit:multa-detail', kwargs={'pk': self.object.id})

@method_decorator(login_required, name='dispatch')
class MultaDeleteView(DeleteView):
    model = Multa
    template_name = 'delete-multa.html'
    success_url = reverse_lazy('transit:multa-list')


##REVISARRRRRR AL LLEGAR A SANTIAGO
@method_decorator(login_required, name='dispatch')
class AutoListView(ListView):
    model = Auto
    template_name = 'listado_auto.html'
    context_object_name = 'autos'
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super(AutoListView, self).get_context_data(**kwargs)
        autos = self.get_queryset()
        page = self.request.GET.get('page')
        paginator = Paginator(autos, self.paginate_by)
        try:
            autos = paginator.page(page)
        except PageNotAnInteger:
            autos = paginator.page(1)
        except EmptyPage:
            autos = paginator.page(paginator.num_pages)
        context['autos'] = autos
        return context

@method_decorator(login_required, name='dispatch')
class AutoCreateView(CreateView):
    model = Auto
    template_name = 'create-auto.html'
    fields = ('patente', 'run_persona_a')

    success_url = reverse_lazy('transit:auto-list')

@method_decorator(login_required, name='dispatch')
class AutoDetailView(DetailView):
    model = Auto
    template_name = 'detail-auto.html'
    context_object_name = 'autos'

@method_decorator(login_required, name='dispatch')
class AutoUpdateView(UpdateView):
    model = Auto
    template_name = 'update_auto.html'
    context_object_name = 'autos'
    fields = ('patente', 'run_persona_a')

Transit_Hualqui/templates/create-multa.html
{% extends "base.html" %}

{% block container %}
<div class="card">
    <div class="card-header">
        <h5 class="card-title">Crear nueva multa</h5>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-success">Crear</button>
        </form>
    </div>
</div>
{% endblock %}

Transit_Hualqui/templates/create.html
{% extends "base.html" %}

{% block container %}
<div class="card">
    <div class="card-header">
        <h5 class="card-title">Crear persona</h5>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-success">Crear</button>
        </form>
    </div>
</div>
{% endblock %}

Transit_Hualqui/templates/delete-apelacion.html
{% extends "base.html" %}
{% block container %}
<div class="card">
    <div class="card-header">
        <h5 class="card-title">Rechazar apelacion {{object.id}}</h5>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            <div class="alert alert-warning" role="alert">
                Seguro de rechazar <strong>{{ object }}</strong> ?
            </div>
            <button type="submit" class="btn btn-danger">Rechazar</button>
        </form>
    </div>
</div>
{% endblock %}

Transit_Hualqui/templates/delete-auto.html
{% extends "base.html" %}
{% block container %}
<div class="card">
    <div class="card-header">
        <h5 class="card-title">Dar de baja Auto {{object.id}}</h5>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            <div class="alert alert-warning" role="alert">
                Seguro de dar de baja <strong>{{ object }}</strong> ?
            </div>
            <button type="submit" class="btn btn-danger">Dar de baja</button>
        </form>
    </div>
</div>
{% endblock %}

Transit_Hualqui/templates/listado_apelacion.html
{% extends "base.html" %}

{% block container %}
<div class="card mb-4">
    <div class="card-header">
      Ayuda
    </div>
    <div class="card-body">
      <blockquote class="blockquote mb-0">
        <p>En este apartado encontrarás todas las apelaciones registradas en la base de datos</p>
      </blockquote>
    </div>
</div>
<table class="table">   
    <tr>
        <thead class="thead-dark">
            <tr>
                <th scope="col">Id multa</th>
                <th scope="col">Rut infractor</th>
                <th scope="col">Descripcion</th>
                <th scope="col">Estado</th>
                <th scope="col">Fecha</th>
                <th scope="col">Detalle</th>
                {% if user.is_superuser %}
                <th scope="col">Aceptar</th>
                <th scope="col">Rechazar</th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for apelacion in apelaciones %}
            <tr>
                    <td>{{apelacion.id_multa_a}}</td>
                    <td>{{apelacion.run_persona_a}}</td>
                    <td>{{apelacion.descripcion}}</td>
                    <td>{{apelacion.estado}}</td>
                    <td>{{apelacion.fecha_hr_a}}</td>
                    <td>
                        <a href="{% url 'transit:apelacion-detail' apelacion.id %}">
                            <i class="fas fa-info" style="color: lightblue; font-size: 1.5rem; text-align: center;"></i>
                        </a>
                    </td>
                    {% if user.is_superuser %}
                    {% if apelacion.estado == 'Por solucionar'%}
                    <td>
                        <a href="{% url 'transit:acept-apelacion' apelacion.id %}">
                            <i class="fas fa-check-circle" style="color: lightblue; font-size: 1.5rem; text-align: center;"></i>
                        </a>
                    </td>
                    <td>
                        <a href="{% url 'transit:reject-apelacion' apelacion.id %}">
                            <i class="fas fa-ban" style="color: red; font-size: 1.5rem; text-align: center;"></i>
                        </a>
                    </td>
                    {% endif %}
                    {% endif %}
                    {% if apelacion.estado == 'Aceptado'%}
                    <td colspan="2"> Aceptada </td>
                    {% endif %}
                    {% if apelacion.estado == 'Rechazado' %}
                    <td colspan="2"> Rechazada </td>
                    {% endif %}
            </tr>
            {% endfor %}
        </tbody>
</table>
<a href="{% url 'transit:apelacion-create' %}">
    <button type="button" class="btn btn-primary">
        <i class="fas fa-plus"> Nueva apelacion</i>
    </button>
</a>
{% if is_paginated %}
    {% include "_pagination.html" %}
{% endif %}

{% endblock %}

Transit_Hualqui/templates/listado_auto.html
{% extends "base.html" %}

{% block container %}
<div class="card mb-4">
    <div class="card-header">
      Ayuda
    </div>
    <div class="card-body">
      <blockquote class="blockquote mb-0">
        <p>En este apartado encontrarás todos los autos registrados en la base de datos</p>
      </blockquote>
    </div>
</div>
<table class="table">   
    <tr>
        <thead class="thead-dark">
            <tr>
                <th scope="col">Patente</th>
                <th scope="col">Rut dueño</th>
                <th scope="col">Detalle</th>
                <th scope="col">Actualizar</th>
                <th scope="col">Eliminar</th>
            </tr>
        </thead>
        <tbody>
            {% for auto in autos %}
            <tr>
                    <td>{{auto.patente}}</td>
                    <td>{{auto.run_persona_a}}</td>
                    <td>
                        <a href="{% url 'transit:auto-detail' auto.id %}">
                            <i class="fas fa-info" style="color: lightblue; font-size: 1.5rem; text-align: center;"></i>
                        </a>
                    </td>
                    <td>
                        <a href="{% url 'transit:auto-update' auto.id %}">
                            <i class="far fa-edit" style="color: yellow; font-size: 1.5rem; text-align: center;"></i>
                        </a>
                    </td>
                    <td>
                        <a href="{% url 'transit:auto-delete' auto.id %}">
                            <i class="fas fa-ban" style="color: red; font-size: 1.5rem; text-align: center;"></i>
                        </a>
                    </td>
            </tr>
            {% endfor %}
        </tbody>
</table>
{% if user.is_superuser%}

<a href="{% url 'transit:auto-create' %}">
    <button type="button" class="btn btn-primary">
        <i class="fas fa-plus"> Nuevo auto</i>
    </button>
</a>
{% endif %}

{% if is_paginated %}
    {% include "_pagination.html" %}
{% endif %}

{% endblock %}

Transit_Hualqui/templates/listado_persona.html
{% extends "base.html" %}

{% block container %}
<div class="card mb-4">
    <div class="card-header">
      Ayuda
    </div>
    <div class="card-body">
      <blockquote class="blockquote mb-0">
        <p>En este apartado encontrarás todas las personas registradas en la base de datos</p>
      </blockquote>
    </div>
</div>
<table class="table">   
    <tr>
        <thead class="thead-dark">
            <tr>
                <th scope="col">Nombre</th>
                <th scope="col">Apellido</th>
                <th scope="col">Edad</th>
                <th scope="col">Rut</th>
                <th scope="col">Estado</th>
                <th scope="col">Detalle</th>
                <th scope="col">Actualizar</th>
                <th scope="col">Dar de baja</th>
            </tr>
        </thead>
        <tbody>
            {% for persona in personas %}
            <tr>
                    <td>{{persona.user.first_name}}</td>
                    <td>{{persona.user.last_name}}</td>
                    <td>{{persona.age}}</td>
                    <td>{{persona.run_persona}}</td>
                    <td>{{persona.estado_verbose}}</td>
                    <td>
                        <a href="{% url 'transit:persona-detail' persona.id %}">
                            <i class="fas fa-info" style="color: lightblue; font-size: 1.5rem; text-align: center;"></i>
                        </a>
                    </td>
                    <td>
                        <a href="{% url 'transit:persona-update' persona.id %}">
                            <i class="far fa-edit" style="color: yellow; font-size: 1.5rem; text-align: center;"></i>
                        </a>
                    </td>
                    <td>
                        <a href="{% url 'transit:persona-delete' persona.id %}">
                            <i class="fas fa-ban" style="color: red; font-size: 1.5rem; text-align: center;"></i>
                        </a>
                    </td>
            </tr>
            {% endfor %}
        </tbody>
</table>
{% if user.is_superuser%}

<a href="{% url 'auth:register' %}">
    <button type="button" class="btn btn-primary">
        <i class="fas fa-plus"> Nueva persona</i>
    </button>
</a>
{% endif %}

{% if is_paginated %}
    {% include "_pagination.html" %}
{% endif %}

{% endblock %}

Transit_Hualqui/templates/usuarios.html
{% extends "base.html" %}

{% block container %}
<div class="card mb-4">
    <div class="card-header">
      Ayuda
    </div>
    <div class="card-body">
      <blockquote class="blockquote mb-0">
        <p>En este apartado encontrarás todos los usuarios registrados en la base de datos</p>
      </blockquote>
    </div>
</div>
<table class="table">   
    <tr>
        <thead class="thead-dark">
            <tr>
                <th scope="col">Nombre</th>
                <th scope="col">Apellido</th>
                <th scope="col">Edad</th>
                <th scope="col">Rut</th>
                <th scope="col">Estado</th>
                <th scope="col">Consultar infracciones</th>
                <th scope="col">Consultar apelaciones</th>
                <th scope="col">Detalle</th>
                <th scope="col">Actualizar</th>
                <th scope="col">Dar de baja</th>
            </tr>
        </thead>
        <tbody>
            {% for persona in personas %}
            <tr>
                    <td>{{persona.user.first_name}}</td>
                    <td>{{persona.user.last_name}}</td>
                    <td>{{persona.age}}</td>
                    <td>{{persona.run_persona}}</td>
                    <td>{{persona.estado_verbose}}</td>
                    <td>
                        <a href="{% url 'transit:usuario-infracciones' persona.id %}">
                            <i class="fas fa-info" style="color: lightblue; font-size: 1.5rem; text-align: center;"></i>
                        </a>
                    </td>
                    <td>
                        <a href="{% url 'transit:usuario-apelaciones' persona.id %}">
                            <i class="fas fa-info" style="color: lightblue; font-size: 1.5rem; text-align: center;"></i>
                        </a>
                    </td>
                    <td>
                        <a href="{% url 'transit:persona-detail' persona.id %}">
                            <i class="fas fa-info" style="color: lightblue; font-size: 1.5rem; text-align: center;"></i>
                        </a>
                    </td>
                    <td>
                        <a href="{% url 'transit:persona-update' persona.id %}">
                            <i class="far fa-edit" style="color: yellow; font-size: 1.5rem; text-align: center;"></i>
                        </a>
                    </td>
                    <td>
                        <a href="{% url 'transit:persona-delete' persona.id %}">
                            <i class="fas fa-ban" style="color: red; font-size: 1.5rem; text-align: center;"></i>
                        </a>
                    </td>
            </tr>
            {% endfor %}
        </tbody>
</table>
{% if user.is_superuser %}
<a href="{% url 'auth:register' %}" class="">
    <button type="button" class="btn btn-primary">
        <i class="fas fa-plus"> Nueva persona</i>
    </button>
</a>
{% endif %}
{% if is_paginated %}
    {% include "_pagination.html" %}
{% endif %}

{% endblock %}