auth_login/urls.py
from django.urls import path, include
from auth_login import views

app_name = 'auth'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('profile/purchases/<int:id>', views.Multas_historial, name='purchases'),
    path('profile/edit', views.editProfile, name='edit'),
    path('profile/change_password', views.change_password, name='change_password'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('transit/', include('Transit_Hualqui.urls')),
    path('auth/', include('auth_login.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

auth_login/models.py
from django.db import models

# Create your models here.

auth_login/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm
Genders = (
	('M', 'Mujer'),
	('H', 'Hombre'),
	('O', 'Otro'),
)


Estados = (
	('In', 'Inactivo'),
	('Ac', 'Activo'),
	('Bl', 'Bloqueado'),
)

class UserForm(forms.Form):
    username = forms.CharField(label='Username')
    rut =  forms.CharField(label='Rut')
    first_name = forms.CharField(label='First name')
    last_name = forms.CharField(label='Last name')
    gender = forms.ChoiceField(label='gender', choices=Genders)
    estado = forms.ChoiceField(label='estado', choices=Estados)
    age = forms.IntegerField()
    birth_date = forms.DateField(label='Birth date', widget=forms.DateInput, help_text="e.g. YYYY-MM-DD")
    email = forms.EmailField(label='E-Mail')
    password =  forms.CharField(label='Password', widget=forms.PasswordInput, max_length=100) 

class EditProfileForm(UserChangeForm):
    def __init__(self, *args, **kwargs):
        super(EditProfileForm, self).__init__(*args, **kwargs)
        del self.fields['password']

    class Meta:
        model = User
        fields = {
            'email',
            'first_name',
            'last_name',
            'password'
        }

auth_login/views.py
from django.shortcuts import render, redirect
from django.contrib import auth, messages
from auth_login.forms import EditProfileForm, UserForm
from django.db import IntegrityError
from django.contrib.auth.models import User
from Transit_Hualqui.models import (
    Apelacion,
    Auto,
    Calle,
    Multa,
    Persona,
    TipoPersona
)
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash

def register(request):
    data = {}
    template_name = 'register.html'
    data['form'] = UserForm(request.POST or None)

    if request.method == 'POST':
        if data['form'].is_valid():
            try:
                user = User.objects.create_user(
                    username=request.POST['username'],
                    first_name=request.POST['first_name'],
                    last_name=request.POST['last_name'],
                    email=request.POST['email'],
                    password=request.POST['password'],
                )

                persona = Persona.objects.create(
                    gender=request.POST['gender'],
                    age=request.POST['age'],
                    run_persona=request.POST['rut'],
                    fecha_nacimiento=request.POST['birth_date'],
                    tipo_persona=TipoPersona.objects.get(id=1),
                    estado=request.POST['estado'],
                    user=user,
                )

                user.save()
                persona.save()

                messages.add_message(
                    request,
                    messages.SUCCESS,
                    'Usuario creado con exito'
                )

            except IntegrityError as ie:
                messages.add_message(
                    request,
                    messages.ERROR,
                    'Problemas al crear el usuario ERROR: {error}.'.format(
                        error=str(ie))
                )

            
        else:
            messages.add_message(
                request,
                messages.ERROR,
                'Problemas al crear usuario',
            )
        return redirect('auth:login')
    return render(request, template_name, data)

def login(request):
    template_name = 'login.html'
    data = {}

    auth.logout(request)
    if request.POST:
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(
            username=username,
            password=password
        )

        if user is not None:
            ## Usuario autenticado
            if user.is_active:
                #Usuario valido
                auth.login(request, user)
                return redirect('transit:home')
            else:
                messages.add_message(
                    request,
                    messages.ERROR,
                    'Error user not active.'
                )
            
        else:
            messages.add_message(
                request,
                messages.ERROR,
                'Usuario o Contraseña incorrectos.'
            )

    return render(request, template_name, data)

def logout(request):
    auth.logout(request)
    return redirect('auth:login')

def profile(request):
    data = {'user': request.user}
    template_name = 'profile.html'
    persona = Persona.objects.get(user=request.user.id)
    data['compras'] = Multa.objects.filter(Persona=persona.id)
    #data['Personas'] = Persona.objects.get(id=2)
    #print(data['Personas'].id)
    #print(request.user.id)
    return render(request, template_name, data)

def editProfile(request):
    data = {}
    template_name = 'edit_profile.html'

    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect('auth:profile')
    else:
        form = EditProfileForm(instance=request.user)
        data = {'form': form}
        return render(request, template_name, data) 


    return render(request, template_name, data)

def change_password(request):
    data = {}
    template_name = 'change_password.html'

    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)
        
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('auth:profile')
        else:
            return redirect('auth:change_password')
    else:
        form = PasswordChangeForm(user=request.user)
        data = {'form': form}
        return render(request, template_name, data) 

def Multas_historial(request, id):
    data = {}
    template_name = 'purchases.html'
    
    data['compras'] = Detail.objects.filter(Numero_boleta=id)
    data['total'] = Multa.objects.get(pk=id)

    return render(request, template_name, data)

auth_login/templates/change_password.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block title %}
Información de tu Perfil
{% endblock %}
{% block content_head %}
<!--Titulo-->
<div class="row round-borderform mt-5 mb-5">
    <div class="col">
        <h2>Cambiar Contraseña</h2>
        <!--Fin titulo-->
        {% endblock %}
        {% block breadcrumb %}
        <li class="breadcrumb-item"><a href="{% url 'auth:register' %}">Perfil</a></li>
        {% endblock %}
        {% block content_body %}
        {% bootstrap_messages %}
        <form method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
            <button type="submit" class="btn btn-primary">
                Cambiar contraseña
            </button>
            {% endbuttons %}
        </form>

    </div>
</div>
{% endblock %}

auth_login/templates/edit_profile.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block title %}
Información de tu Perfil
{% endblock %}
{% block content_head %}
<!--Titulo-->
<div class="row round-borderform mt-5 mb-5">
    <div class="col">
        <h2>Editar perfil</h2>
        <!--Fin titulo-->
        {% endblock %}
        {% block content_body %}
        {% bootstrap_messages %}
        <form method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
            <button type="submit" class="btn btn-primary">
                Confirmar cambios
            </button>
            {% endbuttons %}
        </form>

    </div>
</div>
{% endblock %}

auth_login/templates/login.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}
{% block title %}
Login Usuario
{% endblock %}
{% block content_head %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <form class="form-signin" method="POST">{% csrf_token %}
            <div class="text-center mb-4">
                <h1 class="h3 mb-3 font-weight-normal">User login</h1>
                {% if messages %}
                {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endfor %}
                {% endif %}
            </div>
            <div class="form-label-group">
                <input type="text" id="username" name="username" class="form-control" placeholder="Username" required
                    autofocus>
                <label for="username">Username</label>
            </div>

            <div class="form-label-group">
                <input type="password" id="password" name="password" class="form-control" placeholder="Password"
                    required>
                <label for="password">Password</label>
            </div>

            <div class="checkbox mb-3">
                <label>
                    <input type="checkbox" value="remember-me"> Recuérdame
                </label>
            </div>
            <a href="{% url 'auth:register' %}">Registrarse</a>
            <button class="btn btn-lg btn-primary btn-block mt-2" type="submit">Entrar</button>
            <p class="mt-5 mb-3 text-muted text-center">&copy; 2017-2019</p>
        </form>
    </div>
    <div class="col-3"></div>




{% endblock %}

auth_login/templates/profile.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block title %}
Información de tu Perfil
{% endblock %}
{% block content_head %}
<!--Titulo-->


{% endblock %}
{% block content_body %}
<!--Formulario-->

<div class="row mt-5">
    <div class="col-4">
        <div class="card mb-5" style="width: 19rem;">
            <div class="card-body">
                <h3 class="card-title"><strong>Tus datos</strong></h3>
                <h6>Nombre</h6>
                <p class="card-text">{{user.first_name}} {{user.last_name}}</p>
                <h6>Email</h6>
                <p class="card-text">{{user.email}}</p>
                <a href="{% url 'auth:edit' %}" class="btn btn-primary mr-2"><i class="far fa-edit text-center"></i></a>
                <a href="{% url 'auth:change_password' %}" class="btn btn-primary"><i class="fas fa-key"></i></a>
            </div>
        </div>
        <div class="card mb-5" style="width: 19rem;">
            <div class="card-body">
                <h3 class="card-title"><strong>Direcciones</strong></h3>
                <h6>Casa</h6>
                <p class="card-text">{{user.client.address}}</p>
                <p class="card-text"><i class="fas fa-plus mr-2"></i>Añadir direccion</p>
            </div>
        </div>
    </div>
    <div class="col-8">
        <div class="card mb-5" style="width: 45rem;">
            <div class="card-body">
                <h3 class="card-title"><strong>Tus compras</strong></h3>
                <table class="table mt-4">
                    <thead>
                      <tr>
                        <th scope="col">#</th>
                        <th scope="col">Fecha</th>
                        <th scope="col">Total</th>
                        <th scope="col">Detalle</th>
                      </tr>
                    </thead>
                    <tbody class="table-borderless">
                    {% for compra in compras %}
                      <tr>
                        <td>{{compra.id}}</td>
                        <td>{{compra.date}}</td>
                        <td>${{compra.total}}</td>
                        <td><a href="{% url 'auth:purchases' compra.id %}">Ver Detalle</a></td>
                      </tr>
                    {% endfor %}
                    </tbody>
                  </table>
                <!--If compras ==  0-->

                <!--else-->
                <!--Compras-->
            </div>
        </div>
    </div>
</div>
{% endblock %}


<!-- <div class="row round-borderform">
     <div class="col">
        <h2>Perfil</h2>  -->

auth_login/templates/purchases.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block title %}
Información de tu Perfil
{% endblock %}
{% block content_head %}
<!--Titulo-->


{% endblock %}
{% block content_body %}
<!--Formulario-->

<div class="row mt-5">
    <div class="col-12">
        <div class="card mb-5" style="width: 100%;">
            <div class="card-body">
                <h3 class="card-title"><strong>Tu compra</strong></h3>
                <table class="table mt-4">
                    <thead>
                        <tr>
                            <th scope="col">Producto</th>
                            <th scope="col">Cantidad</th>
                            <th scope="col">Precio</th>
                        </tr>
                    </thead>
                    <tbody class="table-borderless">
                        {% for buy in compras %}
                        <tr>
                            <td>{{buy.product}}</td>
                            <td>{{buy.quantity}}</td>
                            <td>{{buy.product.price}}</td>
                        </tr>
                        {% endfor %}
                        {% if total %}
                        <tr>
                            <td>{{total.total}}</td>
                        </tr>
                        {% endif %}
                    </tbody>
                </table>
                
            </div>
        </div>
    </div>
</div>
{% endblock %}


<!-- <div class="row round-borderform">
     <div class="col">
        <h2>Perfil</h2>  -->

auth_login/templates/register.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block title %}
Crear usuario
{% endblock %}
{% block content_head %}
<!--Titulo-->
<div class="row round-borderform">
    <div class="col">
        <h2>Registrarse</h2>
        <!--Fin titulo-->
        {% endblock %}
        {% block content_body %}
        <!--Formulario-->
        {% bootstrap_messages %}
        <form class="" method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
            <button type="submit" class="btn btn-primary">
                Crear usuario!
            </button>
            {% endbuttons %}
        </form>
        <!--Fin formulario-->
    </div>
</div>
{% endblock %}